### ISSUE TITLE
`coralogix_rules_group` creates rules with OR instead of AND

### ISSUE THREAD

**Issue by Alonreznik** [coralogix/terraform-provider-coralogix#164] opened 2023-10-22 11:07 UTC
resource: `coralogix_rules_group`.
When I'm creating a new rules group via the `coralogix_rules_group` resource, i the rules inside it are created with "OR" condition and not "AND", even though the doc declares it should be created with `AND (&&)`.
![image](https://github.com/coralogix/terraform-provider-coralogix/assets/8024926/5cab8322-2011-4279-8312-4e63fe603678)

And example:

```hcl
resource "coralogix_rules_group" "example" {
name         = "otel-agent-ecs-rule"
  order = 1
rules {
 parse_json_field {
                 active                 = true
                 description            = "Parse the LogRecord.body.log to an object"
                 destination_field      = "text.new_body"
                 keep_destination_field = true
                 keep_source_field      = false
                 name                   = "Parse LogRecord.body.log to obj"
                 source_field           = "text.logRecord.body"
                }
            }
remove_fields {
                active          = true
                description     = "Remove redundant fields"
                 excluded_fields = [
                     "logRecord.body",
                     "new_body",
                      "resourceSchemaUrl"
                    ]
                 name            = "Remove redundant Fields"
                }
}
}
```
![image](https://github.com/coralogix/terraform-provider-coralogix/assets/8024926/bcc7b139-b102-46b9-acdd-8f5d308c278c)

**Comment by OrNovo** [comment] 2023-10-22 11:15
Hi @Alonreznik.
The example you sent is not valid.
Please send an example that goes through the `plan` stage so I can refer to it.

**Comment by Alonreznik** [comment] 2023-10-22 12:22
Hi @OrNovo .
Thanks for the reply.
Please check this next example.

1. Plan:
```tfplan
  # module.coralogix_parsing_rules.coralogix_rules_group.this will be created
  + resource "coralogix_rules_group" "this" {
      + active       = true
      + applications = [
          + "test",
        ]
      + description  = "example for terraform github issue"
      + hidden       = false
      + id           = (known after apply)
      + name         = "test-order-condition"
      + order        = 30
      + severities   = [
          + "Warning",
        ]
      + subsystems   = [
          + "test",
        ]

      + rule_subgroups {
          + active = true
          + id     = (known after apply)
          + order  = (known after apply)

          + rules {
              + remove_fields {
                  + active          = true
                  + description     = "Remove redundant resource attributes"
                  + excluded_fields = [
                      + "resource.attributes.APP_NAME",
                      + "resource.attributes.SUB_SYS",
                    ]
                  + id              = (known after apply)
                  + name            = "Remove redundant resource attributes"
                  + order           = (known after apply)
                }
            }
          + rules {
              + replace {
                  + active             = true
                  + destination_field  = "text"
                  + id                 = (known after apply)
                  + name               = "Replace new log to root"
                  + order              = (known after apply)
                  + regular_expression = "\"new_log\":{(.*?)}(,*?)"
                  + replacement_string = "$1$2"
                  + source_field       = "text"
                }
            }
        }
    }


```
2. Results (after apply):
![image](https://github.com/coralogix/terraform-provider-coralogix/assets/8024926/e7b569ed-cfa7-4572-823c-a51f5be5a129)

**Comment by OrNovo** [comment] 2023-10-22 12:46
@Alonreznik In your example you have a single rule_subgroup with two rules inside.
The rules inside a rule_subgroup have an `or` operator (||), and all the rule_subgroups in a rule_group have `and` operator.
I guess the confusion caused by the structure of the lists in terraform, each `rules` block is actually a single rule (same for `rule_subgroups` blocks).

**Comment by Alonreznik** [comment] 2023-10-22 13:18
Thanks @OrNovo .
Yes. The current documentation is confusing and doesn't have any example that provides AND or OR in it and describes that "Rule-group is list of rule-subgroups with 'and' (&&) operation between. More info: https://coralogix.com/docs/rules-api/". 
Also by referring to the API docs is hard to find the right template we should set in the resource.
I'll fix the resource configuration accordingly in my end. However, it'll be appreciated to fix the documentation here for future confusion.

**Comment by Alonreznik** [comment] 2023-10-22 13:34
Another comment. The current structure of the resource can't provide us the ability to create rule with And condition between the sub-rules under it, using a module. As we must keep the order in place between the sub-rules, there's no option to "modulize" this resource correctly.
Take in consideration the next resource inside the module:
```hcl

resource "coralogix_rules_group" "this" {
  name         = var.parsing_rule_group_name
  description  = var.parsing_rule_group_description
  applications = var.applications
  subsystems   = var.subsystems
  severities   = var.severities
  order        = var.parsing_rule_group_order

  rule_subgroups {
    active = var.is_active

    dynamic "rules" {
      for_each = var.parsing_rules
      content {

        dynamic "remove_fields" {
          for_each = rules.value["type"] == "remove_fields" ? [1] : []
          content {
            name            = rules.value["name"]
            description     = rules.value["description"]
            excluded_fields = rules.value["excluded_fields"]
          }
        }

        dynamic "replace" {
          for_each = rules.value["type"] == "replace" ? [1] : []
          content {
            name               = rules.value["name"]
            description        = rules.value["description"]
            regular_expression = rules.value["regular_expression"]
            source_field       = rules.value["source_field"]
            destination_field  = rules.value["destination_field"]
            replacement_string = rules.value["replacement_string"]
          }
        }

        dynamic "json_extract" {
          for_each = rules.value["type"] == "json_extract" ? [1] : []
          content {
            name              = rules.value["name"]
            description       = rules.value["description"]
            json_key          = rules.value["json_key"]
            destination_field = rules.value["destination_field"]
          }
        }

        dynamic "parse" {
          for_each = rules.value["type"] == "parse" ? [1] : []
          content {
            name               = rules.value["name"]
            description        = rules.value["description"]
            source_field       = rules.value["source_field"]
            destination_field  = rules.value["destination_field"]
            regular_expression = rules.value["regular_expression"]
          }
        }

        dynamic "json_stringify" {
          for_each = rules.value["type"] == "json_stringify" ? [1] : []
          content {
            name              = rules.value["name"]
            description       = rules.value["description"]
            source_field      = rules.value["source_field"]
            destination_field = rules.value["destination_field"]
            keep_source_field = rules.value["keep_source_field"]
          }
        }

        dynamic "block" {
          for_each = rules.value["type"] == "block" ? [1] : []
          content {
            name               = rules.value["name"]
            description        = rules.value["description"]
            source_field       = rules.value["source_field"]
            regular_expression = rules.value["regular_expression"]
          }
        }

        dynamic "extract" {
          for_each = rules.value["type"] == "extract" ? [1] : []
          content {
            name               = rules.value["name"]
            description        = rules.value["description"]
            source_field       = rules.value["source_field"]
            regular_expression = rules.value["regular_expression"]
          }
        }

        dynamic "parse_json_field" {
          for_each = rules.value["type"] == "parse_json_field" ? [1] : []
          content {
            name                   = rules.value["name"]
            description            = rules.value["description"]
            source_field           = rules.value["source_field"]
            destination_field      = rules.value["destination_field"]
            keep_source_field      = rules.value["keep_source_field"]
            keep_destination_field = rules.value["keep_destination_field"]
          }
        }
      }
    }
  }
}
```
The order under `var.parsing_rules` must be kept (it's a list), while we need to create dynamic blocks on each type of rule, which fits the right filter per block.

It makes the modulizing here much more complicated, as need to keep the parsing_rules list order plus keep the right order per each block.

May I ask why not just providing a "type" key inside each "sub_rule" that defines the right type of the sub rule, and provide only one "rule" block with dynamic sub-rules under it?

**Comment by OrNovo** [comment] 2023-10-23 08:09
@Alonreznik each rule type contains different fields, so this will not allow us to validate fields that are required and enforce fields that are not related to the specific rule type defined. However, we are moving to a new terraform-provider development framework that will probably enable your proposal, and we will consider implementing it. Thanks!

**Comment by Alonreznik** [comment] 2023-10-24 11:09
@OrNovo thanks for explaining.

**Closed** 2023-11-02 09:54 UTC
